// Alabama Safari Park — all 31 animals with child-friendly descriptions
export const SAFARI_ANIMALS = [
  {
    id: 'llama',
    name: 'Llama',
    emoji: '🦙',
    wikiTitle: 'Llama',
    origin: 'Llamas come from the tall mountains of South America, in countries like Peru and Bolivia!',
    peculiarity: 'They are very friendly but may spit if they feel upset or scared!',
    funFact: 'A llama can carry up to 110 pounds and walk for miles without getting tired!',
    sound: 'A llama makes a soft, gentle humming sound. Hmmmm!',
  },
  {
    id: 'dromedary-camel',
    name: 'Dromedary Camel',
    emoji: '🐪',
    wikiTitle: 'Dromedary',
    origin: 'Dromedary camels come from the hot deserts of the Middle East and Africa!',
    peculiarity: 'Their one hump stores fat — not water — to fuel long desert journeys!',
    funFact: 'A thirsty camel can drink 30 gallons of water in just 13 minutes!',
    sound: 'A camel makes a deep, grumbly groaning sound. Groooooan!',
  },
  {
    id: 'giraffe',
    name: 'Giraffe',
    emoji: '🦒',
    wikiTitle: 'Giraffe',
    origin: 'Giraffes live in the sunny grasslands and woodlands of Africa!',
    peculiarity: 'They are the tallest animals on Earth and their tongue is 18 inches long and dark blue!',
    funFact: 'A giraffe only needs 5 to 30 minutes of sleep per day — the least of any mammal!',
    sound: 'Giraffes are usually quiet but sometimes make a soft humming sound at night. Hmmmm.',
  },
  {
    id: 'zebra',
    name: 'Zebra',
    emoji: '🦓',
    wikiTitle: 'Plains zebra',
    origin: 'Zebras roam the open grasslands and savannas of Africa in big herds!',
    peculiarity: 'Every zebra has a completely unique stripe pattern — just like your fingerprints!',
    funFact: 'Zebras sleep standing up and can run up to 40 miles per hour!',
    sound: 'A zebra makes a loud barking bray. Kwaa kwaa!',
  },
  {
    id: 'grevys-zebra',
    name: "Grevy's Zebra",
    emoji: '🦓',
    wikiTitle: "Grévy's zebra",
    origin: "Grevy's zebras come from the dry grasslands of Ethiopia and Kenya in Africa!",
    peculiarity: 'They are the largest and most endangered zebra with very narrow stripes and big round ears!',
    funFact: "There are only about 2,500 Grevy's zebras left in the whole wild — they are extremely rare!",
    sound: "A Grevy's zebra makes a loud, raspy roaring bray. Raaawrrr!",
  },
  {
    id: 'ostrich',
    name: 'Ostrich',
    emoji: '🪶',
    wikiTitle: 'Common ostrich',
    origin: 'Ostriches are from the open savannas and deserts of Africa!',
    peculiarity: 'They are the biggest birds in the world but cannot fly — their wings are too small!',
    funFact: 'An ostrich can run at 45 miles per hour — faster than a horse!',
    sound: 'An ostrich makes a deep, thunderous booming sound. Boooom!',
  },
  {
    id: 'emu',
    name: 'Emu',
    emoji: '🪶',
    wikiTitle: 'Emu',
    origin: 'Emus come from the wide open grasslands and forests of Australia!',
    peculiarity: 'Dads sit on the eggs for 8 weeks and look after the babies completely alone!',
    funFact: 'Emus have tiny little wings hidden under their feathers that they cannot use to fly!',
    sound: 'An emu makes a deep booming drum sound. Boom boom boom!',
  },
  {
    id: 'rhea',
    name: 'Rhea',
    emoji: '🪶',
    wikiTitle: 'Greater rhea',
    origin: 'Rheas are from the open grasslands of South America, in countries like Brazil and Argentina!',
    peculiarity: 'Like the ostrich, they cannot fly but can sprint very fast on their long powerful legs!',
    funFact: 'A daddy rhea takes care of as many as 80 eggs at one time in his big nest!',
    sound: 'A rhea makes a low booming call. Booooom!',
  },
  {
    id: 'kangaroo',
    name: 'Kangaroo',
    emoji: '🦘',
    wikiTitle: 'Red kangaroo',
    origin: 'Kangaroos live in the dry outback and grasslands of Australia!',
    peculiarity: 'Baby kangaroos, called joeys, are born tiny like a jellybean and grow inside mom\'s pouch!',
    funFact: 'A kangaroo can hop at 35 miles per hour and leap 6 feet high in one jump!',
    sound: 'A kangaroo makes a soft clucking or clicking sound. Click click!',
  },
  {
    id: 'bison',
    name: 'Bison',
    emoji: '🦬',
    wikiTitle: 'American bison',
    origin: 'Bison once roamed the great plains of North America in enormous herds of millions!',
    peculiarity: 'The big hump on their back is pure muscle that helps them plow through deep snow like a snowplow!',
    funFact: 'Bison are the largest land animals in North America — they can weigh up to 2,000 pounds!',
    sound: 'A bison makes a deep, rumbling grunt. Ugh ugh!',
  },
  {
    id: 'waterbuck',
    name: 'Waterbuck',
    emoji: '🫎',
    wikiTitle: 'Waterbuck',
    origin: 'Waterbucks live near rivers and lakes across sub-Saharan Africa!',
    peculiarity: 'They have a white circle on their rump that looks just like a toilet seat!',
    funFact: 'Their fur makes a special waterproof oil that helps keep insects and predators away!',
    sound: 'A waterbuck makes a soft snorting grunt. Hnng!',
  },
  {
    id: 'eland',
    name: 'Eland',
    emoji: '🫎',
    wikiTitle: 'Common eland',
    origin: 'Elands live across the savannas and grasslands of eastern and southern Africa!',
    peculiarity: 'They are the largest antelope in the world — almost as big as a cow!',
    funFact: 'An eland can jump over a fence taller than your dad from a completely standing start!',
    sound: 'An eland makes a clicking sound when it walks and deep grunting calls. Click grunt!',
  },
  {
    id: 'greater-kudu',
    name: 'Greater Kudu',
    emoji: '🫎',
    wikiTitle: 'Greater kudu',
    origin: 'Greater kudus live in the woodlands and scrublands of eastern and southern Africa!',
    peculiarity: 'Males have magnificent spiral horns that twist around 2 and a half times!',
    funFact: 'Kudus can jump 2.5 meters high — that is almost the height of a basketball hoop!',
    sound: 'A kudu makes a deep, loud alarm bark when it senses danger. BARK!',
  },
  {
    id: 'blackbuck',
    name: 'Blackbuck',
    emoji: '🫎',
    wikiTitle: 'Blackbuck',
    origin: 'Blackbucks come from the open grasslands and forests of India!',
    peculiarity: 'Male blackbucks are dark brown to black on top with a bright white belly!',
    funFact: 'Blackbucks are one of the fastest animals on land — they can run at nearly 50 miles per hour!',
    sound: 'A blackbuck makes a soft snorting grunt. Snort!',
  },
  {
    id: 'arabian-oryx',
    name: 'Arabian Oryx',
    emoji: '🫎',
    wikiTitle: 'Arabian oryx',
    origin: 'Arabian oryxes come from the hot deserts and dry grasslands of the Middle East!',
    peculiarity: 'They went completely extinct in the wild but were saved by zoos and brought back to life in the desert!',
    funFact: 'An Arabian oryx can sense rain coming from very far away and walk miles to find it!',
    sound: 'An Arabian oryx makes a quiet snorting grunt. Snnrt!',
  },
  {
    id: 'fallow-deer',
    name: 'Fallow Deer',
    emoji: '🦌',
    wikiTitle: 'Fallow deer',
    origin: 'Fallow deer originally come from the Middle East but now live in parks across Europe!',
    peculiarity: 'Their antlers are shaped like the palm of a hand — scientists call this palmate antlers!',
    funFact: 'Baby fallow deer are called fawns and have white spots to help them hide in dappled sunlight!',
    sound: 'A fallow deer makes a deep belching groan during the autumn. Groan!',
  },
  {
    id: 'nilgai',
    name: 'Nilgai',
    emoji: '🫎',
    wikiTitle: 'Nilgai',
    origin: 'Nilgai are the largest Asian antelopes and come from the plains of India and Nepal!',
    peculiarity: 'They are called Blue Bulls because adult males turn a beautiful blue-grey color!',
    funFact: 'Nilgai can go for long periods without water by getting moisture from the plants they eat!',
    sound: 'A nilgai makes a low, cow-like moo sound. Moooo!',
  },
  {
    id: 'nile-lechwe',
    name: 'Nile Lechwe',
    emoji: '🫎',
    wikiTitle: 'Nile lechwe',
    origin: 'Nile lechwes live in the swampy floodplains along the Nile River in South Sudan and Ethiopia!',
    peculiarity: 'Their back legs are longer than their front legs, making them look like they are going downhill!',
    funFact: 'They make very unusual sounds that are a mix between a frog and a pig!',
    sound: 'A Nile lechwe makes a croaky snorting sound. Croak snort!',
  },
  {
    id: 'red-lechwe',
    name: 'Red Lechwe',
    emoji: '🫎',
    wikiTitle: 'Red lechwe',
    origin: 'Red lechwes live in the flooded grasslands and wetlands of Central Africa!',
    peculiarity: 'Their legs are coated in a special waterproof oil that lets them sprint through water!',
    funFact: 'Red lechwes spend so much time in water that they have become excellent swimmers!',
    sound: 'A red lechwe makes a soft bleating sound. Bleat!',
  },
  {
    id: 'black-wildebeest',
    name: 'Black Wildebeest',
    emoji: '🐃',
    wikiTitle: 'Black wildebeest',
    origin: 'Black wildebeests are from the open plains and grasslands of South Africa!',
    peculiarity: 'They have horns that curve forward like handlebars and a mane of stiff hair on their face!',
    funFact: 'Their other name is White-tailed Gnu — which is one of the most fun animal names to say!',
    sound: 'A black wildebeest makes loud snorting and grunting sounds. Snort grunt!',
  },
  {
    id: 'blue-wildebeest',
    name: 'Blue Wildebeest',
    emoji: '🐃',
    wikiTitle: 'Blue wildebeest',
    origin: 'Blue wildebeests roam the savannas and grasslands of eastern and southern Africa!',
    peculiarity: 'They make one of the greatest migrations on Earth — over one million wildebeest move together!',
    funFact: 'Baby wildebeest can stand up and run within just a few minutes of being born!',
    sound: 'A blue wildebeest makes a deep moaning, gnu-ing call. Gnuuuu!',
  },
  {
    id: 'water-buffalo',
    name: 'Water Buffalo',
    emoji: '🐃',
    wikiTitle: 'Water buffalo',
    origin: 'Water buffalos come from the wetlands and grasslands of South Asia!',
    peculiarity: 'They love rolling in muddy water to cool down and to protect their skin from biting insects!',
    funFact: 'There are more than 180 million water buffalos in the world — they help farmers in rice fields!',
    sound: 'A water buffalo makes a very deep, loud moo. Moooooo!',
  },
  {
    id: 'banteng',
    name: 'Banteng',
    emoji: '🐂',
    wikiTitle: 'Banteng',
    origin: 'Bantengs are wild cattle from the tropical forests of Southeast Asia, like Borneo and Java!',
    peculiarity: 'They have white stockings on their lower legs that look like they are wearing socks!',
    funFact: 'Female bantengs are reddish-brown but males turn almost completely black as they grow up!',
    sound: 'A banteng makes deep, cow-like mooing sounds. Mooooo!',
  },
  {
    id: 'scottish-highland-cattle',
    name: 'Highland Cow',
    emoji: '🐄',
    wikiTitle: 'Highland cattle',
    origin: 'Highland cows come from the cold, rugged Highlands of Scotland!',
    peculiarity: 'Their long, shaggy hair acts like a raincoat, keeping them warm and dry in stormy weather!',
    funFact: 'Highland cows have two layers of hair — a woolly undercoat and a long oily outer coat!',
    sound: 'A highland cow makes a gentle, deep moo. Mooooo!',
  },
  {
    id: 'watusi',
    name: 'Watusi Cattle',
    emoji: '🐄',
    wikiTitle: 'Ankole-Watusi',
    origin: 'Watusi cattle come from the Great Lakes region of central Africa and are an ancient breed!',
    peculiarity: 'Their gigantic horns can measure up to 8 feet from tip to tip — the widest of any cattle!',
    funFact: 'The horns have blood vessels inside that work like a radiator to cool the animal down in the heat!',
    sound: 'A watusi makes a low grunt and a gentle moo. Grunt moooo!',
  },
  {
    id: 'giant-anteater',
    name: 'Giant Anteater',
    emoji: '🐜',
    wikiTitle: 'Giant anteater',
    origin: 'Giant anteaters come from the grasslands and forests of Central and South America!',
    peculiarity: 'Their tongue is 2 feet long and can flick in and out 150 times per minute to catch bugs!',
    funFact: 'A giant anteater has no teeth and eats up to 35,000 ants and termites every single day!',
    sound: 'A giant anteater makes a low snuffling sound as it searches the ground. Snuffle snuffle!',
  },
  {
    id: 'aldabra-tortoise',
    name: 'Aldabra Tortoise',
    emoji: '🐢',
    wikiTitle: 'Aldabra giant tortoise',
    origin: 'Aldabra tortoises come from a tiny group of islands called the Aldabra Atoll in the Indian Ocean!',
    peculiarity: 'They are one of the longest-living animals on Earth and can live for more than 150 years!',
    funFact: 'They weigh up to 550 pounds — that is as heavy as four grown-up people standing on a scale!',
    sound: 'An Aldabra tortoise is mostly quiet but makes soft grunting sounds when eating. Munch munch!',
  },
  {
    id: 'two-toed-sloth',
    name: 'Two-Toed Sloth',
    emoji: '🦥',
    wikiTitle: "Hoffmann's two-toed sloth",
    origin: 'Two-toed sloths live high in the rainforest trees of Central and South America!',
    peculiarity: 'They hang upside down from tree branches almost all the time — even when they sleep and eat!',
    funFact: 'Sloths only climb down from their tree about once a week to go to the bathroom!',
    sound: 'A sloth makes a quiet, high-pitched squealing sound when it is scared. Eeeee!',
  },
  {
    id: 'tufted-capuchin',
    name: 'Tufted Capuchin',
    emoji: '🐒',
    wikiTitle: 'Tufted capuchin',
    origin: 'Tufted capuchin monkeys come from the tropical forests of South America!',
    peculiarity: 'They are one of the smartest monkeys and use rocks as tools to crack open hard nuts!',
    funFact: 'Capuchins rub certain plants and insects on their fur to keep mosquitoes and bugs away!',
    sound: 'A capuchin monkey chatters and makes sharp whistling calls. Chitter chitter!',
  },
  {
    id: 'lemur',
    name: 'Ring-tailed Lemur',
    emoji: '🐾',
    wikiTitle: 'Ring-tailed lemur',
    origin: 'Ring-tailed lemurs come from the island of Madagascar, just off the coast of Africa!',
    peculiarity: 'They have striking black and white striped tails they hold up like flags to talk to their friends!',
    funFact: 'Lemurs sunbathe every morning by sitting with their tummy facing the sun like little solar panels!',
    sound: 'A ring-tailed lemur makes loud cat-like meowing and wailing calls. Meeow waaah!',
  },
  {
    id: 'parakeet',
    name: 'Parakeet',
    emoji: '🦜',
    wikiTitle: 'Budgerigar',
    origin: 'Parakeets originally come from the dry grasslands and scrublands of Australia!',
    peculiarity: 'They can learn to say real words and short sentences — some can say hundreds of words!',
    funFact: 'In the wild, budgerigars travel in enormous flocks of thousands of birds across the Australian outback!',
    sound: 'A parakeet chirps, tweets and chatters happily. Tweet tweet chirp!',
  },
];
