// High Museum of Art — permanent highlights + current exhibitions (May 2026)
// Each item has a kid-friendly hunt clue Rowan can use to find it by sight
// directImg: direct image URL from High Museum servers (preferred over Wikipedia API)
export const MUSEUM_ITEMS = [
  {
    id: 'taago',
    name: 'Taago',
    artist: 'El Anatsui',
    emoji: '✨',
    wikiTitle: 'El Anatsui',
    directImg: 'https://dlc.services/iiif-img/16/6/17365_1760068999224/full/1024,768/0/default.jpg',
    huntClue: 'Find a GIANT shiny wall that looks like it\'s made of gold and silver!',
    where: 'Lobby / Wieland Pavilion',
    about: 'El Anatsui grew up in Ghana in West Africa. He connected thousands of recycled aluminum bottle caps with copper wire to make this enormous shimmering wall hanging.',
    whyCool: 'It looks like a shiny gold cloth from far away — but get close and you can see every little bottle cap! His dad was a master kente cloth weaver, and this artwork honors that tradition.',
    funFact: 'This artwork is made from bottle caps collected near breweries in Nigeria — the same caps that once sealed cold drinks!',
    sound: 'The bottle caps make a soft tinkling sound when the air gently moves through them.',
  },
  {
    id: 'red-canna',
    name: 'Red Canna',
    artist: 'Georgia O\'Keeffe',
    emoji: '🌺',
    wikiTitle: 'Red Canna',
    directImg: 'https://highmuseum-redesign.s3.us-east-1.amazonaws.com/datasync/collection-objects/5673_1767819725622.jpg',
    huntClue: 'Find a painting of a HUGE red flower that fills the whole canvas!',
    where: 'American Art galleries',
    about: 'Georgia O\'Keeffe was an American artist who loved painting flowers, deserts, and the wide open sky. She painted this when she saw red canna lilies on a vacation in New York.',
    whyCool: 'O\'Keeffe zoomed all the way in on the flower so you can see every petal and curve — it\'s like looking at it through a magnifying glass! She wanted you to really see how beautiful one flower can be.',
    funFact: 'Georgia O\'Keeffe painted over 200 flower paintings in her lifetime — she loved them so much!',
    sound: 'If you listen carefully in the garden, canna lilies rustle softly in the breeze.',
  },
  {
    id: 'house-iii',
    name: 'House III',
    artist: 'Roy Lichtenstein',
    emoji: '🏠',
    wikiTitle: 'Roy Lichtenstein',
    directImg: 'https://highmuseum-redesign.s3.us-east-1.amazonaws.com/datasync/collection-objects/15257_1732715004649.jpg',
    huntClue: 'Find a small house sculpture that looks DIFFERENT depending on where you stand!',
    where: 'Modern & Contemporary Art',
    about: 'Roy Lichtenstein was an American artist famous for making art that looked like it came from comic books and cartoons. He made this little house to play a trick on your eyes.',
    whyCool: 'It\'s an optical illusion! Walk slowly around it and the house shape changes. It\'s smaller than a real house — like a toy you can walk around!',
    funFact: 'Lichtenstein is also famous for making giant paintings with bold colors and black dot patterns — just like a blown-up comic book panel!',
    sound: 'If a real house that small existed, it would be a perfect home for a mouse!',
  },
  {
    id: 'physic-garden',
    name: 'Physic Garden',
    artist: 'Molly Hatch',
    emoji: '🌿',
    wikiTitle: 'Molly Hatch',
    directImg: 'https://dlc.services/iiif-img/16/6/26313_1727025768127/full/683,1024/0/default.jpg',
    huntClue: 'Find a WALL covered in hundreds and hundreds of painted ceramic plates!',
    where: 'Decorative Arts galleries',
    about: 'Molly Hatch is an American artist and ceramicist from Massachusetts. She painted 465 individual ceramic plates by hand to create this enormous wall installation.',
    whyCool: 'She was inspired by old antique plates from the Chelsea Physic Garden in England from the 1700s. Each plate has flowers, leaves, and insects painted on it — together they make one huge garden on the wall!',
    funFact: 'Molly Hatch painted 465 individual plates — that\'s more plates than most people wash in a whole year!',
    sound: 'Ceramic plates make a gentle clink sound when they touch together.',
  },
  {
    id: 'chest-of-drawers',
    name: 'You Can\'t Lay Down Your Memory',
    artist: 'Tejo Remy',
    emoji: '🗄️',
    wikiTitle: 'Tejo Remy',
    directImg: 'https://dlc.services/iiif-img/16/6/18481_1727029281398/full/981,1024/0/default.jpg',
    huntClue: 'Find a wobbly tower of 20 old drawers all strapped together with a belt!',
    where: 'Decorative Arts galleries',
    about: 'Tejo Remy is a Dutch designer from the Netherlands. He collected 20 old drawers that were donated by real families from Georgia and stacked them all together.',
    whyCool: 'Each drawer holds memories of real people — toys, letters, photos, buttons — and together they make a funny, lopsided sculpture held together by one big leather belt. It\'s a whole stack of different people\'s stories!',
    funFact: 'The Georgia families who donated the drawers each got to keep one special thing from inside — everything else became part of the artwork!',
    sound: 'Old wooden drawers make a creaking, sliding sound when you open and close them.',
  },
  {
    id: 'monet-cliffs',
    name: 'Cliffs of Pourville, Rough Sea',
    artist: 'Claude Monet',
    emoji: '🌊',
    wikiTitle: 'Cliffs at Pourville',
    directImg: 'https://dlc.services/iiif-img/16/6/37184_1764957876048/full/1024,666/0/default.jpg',
    huntClue: 'Find a painting of stormy ocean waves made with THICK, wiggly brushstrokes!',
    where: 'European Art galleries',
    about: 'Claude Monet was a French artist who helped start a style called Impressionism. He loved painting outside in the sun, wind, and rain to capture how light changes everything.',
    whyCool: 'Instead of painting thin, careful lines, Monet used thick blobs of color brushed together quickly — like your fingers painting on paper! Up close it looks like smudges; far away it looks like a real stormy sea.',
    funFact: 'Monet painted outdoors in all kinds of weather — even winter storms — because he wanted to show exactly how the light looked at that moment!',
    sound: 'Crashing waves make a loud WHOOOOSH and spray cool mist everywhere!',
  },
  {
    id: 'noguchi',
    name: 'Isamu Noguchi Sculptures',
    artist: 'Isamu Noguchi',
    emoji: '🪨',
    wikiTitle: 'Isamu Noguchi',
    directImg: 'https://highmuseum-redesign.s3.amazonaws.com/uploads/2026/04/XLNOG049-Noguchi-Seraphic-Dialogue_O4.jpg',
    huntClue: 'Find smooth, abstract stone or metal sculptures that look like nothing — and everything!',
    where: 'Special Exhibition',
    about: 'Isamu Noguchi was a Japanese-American artist and designer born in Los Angeles. He created sculptures, furniture, gardens, and even playgrounds!',
    whyCool: 'Noguchi\'s sculptures are smooth and abstract — they don\'t look exactly like any one thing. He wanted you to let your imagination run free and decide what each shape means to you. Some look like rocks, some like clouds, some like creatures!',
    funFact: 'Noguchi also designed the famous Akari paper lanterns — the glowing rice-paper lights you see in Japanese restaurants!',
    sound: 'Stone makes a low, hollow knock sound when you gently tap it with a knuckle.',
  },
  {
    id: 'minnie-evans',
    name: 'Minnie Evans Drawings',
    artist: 'Minnie Evans',
    emoji: '🌈',
    wikiTitle: 'Minnie Evans',
    directImg: 'https://highmuseum-redesign.s3.amazonaws.com/uploads/2025/10/EXME75.8.1-Evans_O3-1024x722.jpg',
    huntClue: 'Find drawings bursting with wild colors, faces, flowers, and swirling patterns!',
    where: 'Special Exhibition — The Lost World',
    about: 'Minnie Evans was a self-taught American artist from North Carolina. She worked as a gate attendant at an arboretum (a big garden with trees) and made her art in her spare time.',
    whyCool: 'Evans said her colorful, dreamlike pictures came to her in visions! They are full of faces, flowers, angels, birds, and magical patterns all swirling together. No one had ever made art quite like hers.',
    funFact: 'Minnie Evans didn\'t start making art until she was 43 years old — it\'s never too late to create something amazing!',
    sound: 'Looking at her art feels like music — colorful and joyful!',
  },
  {
    id: 'african-art',
    name: 'African Art Collection',
    artist: 'Various African Artists',
    emoji: '🥁',
    wikiTitle: 'African art',
    huntClue: 'Find colorful masks, wooden carvings, or textiles from countries across Africa!',
    where: 'African Art galleries — Skyway Level',
    about: 'The High Museum has a wonderful collection of art from all across the African continent, spanning thousands of years from ancient times right up to today.',
    whyCool: 'African art takes so many forms — carved wooden masks used in ceremonies, brightly woven kente cloth, bronze sculptures, and beaded jewelry. Each piece tells the story of the people and culture that made it.',
    funFact: 'West African kente cloth is woven in narrow strips and then sewn together — the patterns and colors have special meanings in the culture!',
    sound: 'African drums make a deep, resonant boom-boom sound that you can feel in your chest!',
  },
  {
    id: 'bellini-madonna',
    name: 'Madonna and Child',
    artist: 'Giovanni Bellini',
    emoji: '👶',
    wikiTitle: 'Giovanni Bellini',
    directImg: 'https://dlc.services/iiif-img/16/6/6891_1727037199503/full/793,1024/0/default.jpg',
    huntClue: 'Find a very old painting of a mother gently holding her baby!',
    where: 'European Art — Renaissance galleries',
    about: 'Giovanni Bellini was an Italian painter who lived in Venice more than 500 years ago. He was one of the most important artists of the Renaissance, a time when European art was being transformed.',
    whyCool: 'Bellini made his figures look soft and real — not stiff like older paintings. The faces show real feelings: love, tenderness, and calm. This painting is over 500 years old and still looks beautiful!',
    funFact: 'Bellini\'s paintings influenced the great artist Titian, who became one of history\'s most famous painters — Bellini was his teacher!',
    sound: 'Paintings are silent, but if you look carefully at this one you can almost imagine a lullaby.',
  },
  {
    id: 'renoir-still-life',
    name: 'Still-Life with Apples',
    artist: 'Pierre-Auguste Renoir',
    emoji: '🍎',
    wikiTitle: 'Pierre-Auguste Renoir',
    directImg: 'https://dlc.services/iiif-img/16/6/16541_1727030837729/full/1024,371/0/default.jpg',
    huntClue: 'Find a painting of red and green apples that look almost good enough to eat!',
    where: 'European Art — Impressionism',
    about: 'Pierre-Auguste Renoir was a French Impressionist artist who loved painting people enjoying life, landscapes, and everyday objects like fruit. He was friends with Claude Monet.',
    whyCool: 'Renoir used warm, glowing colors and soft brushstrokes to make the apples look round and real. Impressionist artists painted what the eye actually sees — soft edges, changing light, and vibrant color!',
    funFact: 'Renoir painted over 4,000 paintings in his lifetime — even when his hands hurt from arthritis, he had brushes tied to his wrists so he could keep painting!',
    sound: 'Apples make a satisfying crunch when you bite into them — crunch!',
  },
];
